### ISSUE TITLE
easy_install github-tools failed

### ISSUE THREAD

**Issue by lidaobing** [dinoboff/github-tools#2]
<pre>
$ sudo easy_install github-tools
[snip]
byte-compiling /usr/local/lib/python2.6/dist-packages/PasteScript-1.7.3-py2.6.egg/paste/script/util/__init__.py to __init__.pyc                                  
byte-compiling /usr/local/lib/python2.6/dist-packages/PasteScript-1.7.3-py2.6.egg/paste/script/paster-templates/basic_package/+package+/__init__.py to __init__.pyc                                                                                                                                                               
byte-compiling /usr/local/lib/python2.6/dist-packages/PasteScript-1.7.3-py2.6.egg/paste/script/wsgiserver/__init__.py to __init__.pyc                            
Adding PasteScript 1.7.3 to easy-install.pth file                                                                                                                
Installing paster script to /usr/local/bin                                                                                                                       
Installing paster script to /usr/local/bin                                                                                                                       

Installed /usr/local/lib/python2.6/dist-packages/PasteScript-1.7.3-py2.6.egg
Searching for Paver                                                         
Reading http://pypi.python.org/simple/Paver/                                
Reading http://www.blueskyonmars.com/projects/paver/                        
Best match: Paver 1.0.1                                                     
Downloading http://pypi.python.org/packages/source/P/Paver/Paver-1.0.1.tar.gz#md5=f53d1d5ed6517e6def1926f7918a02ec
Processing Paver-1.0.1.tar.gz                                                                                     
Running Paver-1.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-_STP3h/Paver-1.0.1/egg-dist-tmp-jZoA45     
Traceback (most recent call last):                                                                                
  File "/usr/bin/easy_install", line 8, in <module>                                                               
    load_entry_point('setuptools==0.6c9', 'console_scripts', 'easy_install')()                                    
  File "/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line 1717, in main                  
    with_ei_usage(lambda:                                                                                         
  File "/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line 1705, in with_ei_usage         
    return f()                                                                                                    
  File "/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line 1721, in <lambda>              
    distclass=DistributionWithoutHelpCommands, **kw                                                               
  File "/usr/lib/python2.6/distutils/core.py", line 152, in setup                                                 
    dist.run_commands()                                                                                           
  File "/usr/lib/python2.6/distutils/dist.py", line 975, in run_commands                                          
    self.run_command(cmd)                                                                                         
  File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command                                           
    cmd_obj.run()                                                                                                 
  File "/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line 229, in run                    
    self.easy_install(spec, not self.no_deps)                                                                     
  File "/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line 464, in easy_install           
    return self.install_item(spec, dist.location, tmpdir, deps)                                                   
  File "/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line 496, in install_item           
    self.process_distribution(spec, dist, deps)                                                                   
  File "/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line 537, in process_distribution   
    [requirement], self.local_index, self.easy_install                                                            
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 522, in resolve                                  
    dist = best[req.key] = env.best_match(req, self, installer)                                                   
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 758, in best_match                               
    return self.obtain(req, installer) # try and download/install                                                 
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 770, in obtain                                   
    return installer(requirement)                                                                                 
  File "/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line 464, in easy_install           
    return self.install_item(spec, dist.location, tmpdir, deps)                                                   
  File "/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line 494, in install_item           
    dists = self.install_eggs(spec, download, tmpdir)                                                             
  File "/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line 673, in install_eggs           
    return self.build_and_install(setup_script, setup_base)                                                       
  File "/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line 948, in build_and_install      
    self.run_setup(setup_script, setup_base, args)                                                                
  File "/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line 937, in run_setup              
    run_setup(setup_script, args)                                                                                 
  File "/usr/lib/python2.6/dist-packages/setuptools/sandbox.py", line 27, in run_setup                            
    lambda: execfile(                                                                                             
  File "/usr/lib/python2.6/dist-packages/setuptools/sandbox.py", line 63, in run                                  
    return func()                                                                                                 
  File "/usr/lib/python2.6/dist-packages/setuptools/sandbox.py", line 29, in <lambda>                             
    {'__file__':setup_script, '__name__':'__main__'}                                                              
  File "setup.py", line 7, in <module>                                                                            
    'bbw-local-crawler = blc.core.bin:main',                                                                      
  File "paver-minilib.zip/paver/tasks.py", line 615, in main                                                      
  File "paver-minilib.zip/paver/tasks.py", line 595, in _launch_pavement                                          
  File "pavement.py", line 5, in <module>                                                                         
ImportError: No module named doctools            
</pre>

**Comment by dinoboff** [comment]
It seems that paver can't install paver when using the default minilib.py. You need to add paver.doctools and paver.virtualenv to minilib if paver is in the list of required distribution.

**Comment by dinoboff** [comment]
fixed with github-tools v0.1.3
