### ISSUE TITLE
GitCommandError when "paster create -t gh_package project_name"

### ISSUE THREAD

**Issue by jinglemansweep** [dinoboff/github-tools#5]
[user@neutrino Python]$ paster create -t gh_package myproject
Traceback (most recent call last):
  File "/usr/bin/paster", line 8, in <module>
    load_entry_point('PasteScript==1.7.3', 'console_scripts', 'paster')()
  File "/usr/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/command.py", line 84, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/command.py", line 123, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/command.py", line 218, in run
    result = self.command()
  File "/usr/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/create_distro.py", line 73, in command
    self.extend_templates(templates, tmpl_name)
  File "/usr/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/create_distro.py", line 262, in extend_templates
    tmpl = entry.load()(entry.name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1913, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/python2.6/site-packages/github_tools-0.1.4-py2.6.egg/github/tools/template.py", line 114, in <module>
    DEFAULT_NAME = Git(os.getcwd()).config('user.name').strip()
  File "build/bdist.linux-x86_64/egg/git/cmd.py", line 34, in <lambda>

  File "build/bdist.linux-x86_64/egg/git/cmd.py", line 183, in _call_process
    return None, None, line
  File "build/bdist.linux-x86_64/egg/git/cmd.py", line 109, in execute
    self.preloop()
git.errors.GitCommandError: "['git', 'config', 'user.name'] returned exit status 1"

**Comment by dinoboff** [comment]
Paster cannot create the a gh_template project when git config variable user.name (or user.email) is not set. I will fix it in v0.1.5

In the mean time, you should set git user name and email:

```
git config --global user.name "jingleman"
git config --global user.email "jingleman@example.com"
```

**Comment by dinoboff** [comment]
losed by 78b7306c847906c025f60f12a4b89ecf0c59b00f

Having user.name and user.email git config variables set
should not be mandatory.

**Comment by jyr** [comment]
I tried with git config --global user.name "myuser" not works, follows the error. I use osx

**Comment by jyr** [comment]
Works with: 
git config --global github.user "youruser"
git config --global github.token "youtoken"

**Comment by dinoboff** [comment]
Hi,

What was the error message?
