### ISSUE TITLE
Can't add submodule for the documentation

### ISSUE THREAD

**Issue by mattions** [dinoboff/github-tools#9]
Hi, 

I'm trying to add the gh-pages for my project, but I've got an error:
    mattions@triton:neuronvisio(master)$ paver gh_pages_create
    ---> github.tools.task.gh_pages_create
    Create a submodule at docs/_build/html and a gh-pages root branch to host your gh-pages...

```
Captured Task Output:
---------------------

---> github.tools.task.gh_pages_create
Create a submodule at docs/_build/html and a gh-pages root branch to host your gh-pages...
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/Paver-1.0.1-py2.6.egg/paver/tasks.py", line 164, in _run_task
    return do_task()
  File "/usr/local/lib/python2.6/dist-packages/Paver-1.0.1-py2.6.egg/paver/tasks.py", line 161, in do_task
    return func(**kw)
  File "/usr/local/lib/python2.6/dist-packages/github_tools-0.2b1-py2.6.egg/github/tools/task.py", line 120, in gh_pages_create
    remote_name=remote_name)
  File "/usr/local/lib/python2.6/dist-packages/Paver-1.0.1-py2.6.egg/paver/easy.py", line 16, in dry
    return func(*args, **kw)
  File "/usr/local/lib/python2.6/dist-packages/github_tools-0.2b1-py2.6.egg/github/tools/gh_pages.py", line 220, in add_gh_pages_submodule
    self.submodules.add(project_url, gh_pages_path)
  File "/usr/local/lib/python2.6/dist-packages/github_tools-0.2b1-py2.6.egg/github/tools/gh_pages.py", line 290, in add
    self.__setitem__(path, module)
  File "/usr/local/lib/python2.6/dist-packages/github_tools-0.2b1-py2.6.egg/github/tools/gh_pages.py", line 282, in __setitem__
    module.init()
  File "/usr/local/lib/python2.6/dist-packages/github_tools-0.2b1-py2.6.egg/github/tools/gh_pages.py", line 257, in init
    self.repo.git.submodule('add', self.url, self.path)
  File "build/bdist.linux-i686/egg/git/cmd.py", line 34, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "build/bdist.linux-i686/egg/git/cmd.py", line 183, in _call_process
    return self.execute(call, **_kwargs)
  File "build/bdist.linux-i686/egg/git/cmd.py", line 109, in execute
    raise GitCommandError(command, status, stderr_value)
GitCommandError: "['git', 'submodule', 'add', 'git@github.com:mattions/neuronvisio.git', 'docs/_build/html'] returned exit status 1"
```

I'm using the 0.2b1

**Comment by mattions** [comment]
forget it. It worked.
